//ITEMS

export const ADD_USER = 'ADD_USER'
export const DELETE_USER = 'DELETE_USER'
export const UPDATE_USER = 'UPDATE_USER'
export const GET_USER = 'GET_USER'
export const CURRENT_USER = 'CURRENT_USER'

//ITEMS
export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const UPDATE_ITEM = 'UPDATE_ITEM'
export const GET_ITEM = 'GET_ITEM'
export const CURRENT_ITEM = 'GET_ITEM'

export const ADD_STORE = 'ADD_STORE'
export const DELETE_STORE = 'DELETE_STORE'
export const UPDATE_STORE = 'UPDATE_STORE'
export const GET_STORE = 'GET_ITEM'
export const CURRENT_STORE = 'GET_ITEM'

export const ADD_TRANSACTION = 'ADD_TRANSACTION'
export const DELETE_TRANSACTION = 'DELETE_TRANSACTION'
export const UPDATE_TRANSACTION = 'UPDATE_TRANSACTION'
export const GET_TRANSACTION = 'GET_TRANSACTION'
export const CURRENT_TRANSACTION = 'GET_TRANSACTION'

export const ADD_MANAGER = 'ADD_TRANSACTION'
export const DELETE_MANAGER = 'DELETE_TRANSACTION'
export const UPDATE_MANAGER = 'UPDATE_TRANSACTION'
export const GET_MANAGER = 'GET_TRANSACTION'
export const CURRENT_MANAGER = 'GET_TRANSACTION'

export const ADD_EMPLOYEE = 'ADD_TRANSACTION'
export const DELETE_EMPLOYEE = 'DELETE_TRANSACTION'
export const UPDATE_EMPLOYEE = 'UPDATE_TRANSACTION'
export const GET_EMPLOYEE = 'GET_TRANSACTION'
export const CURRENT_EMPLOYEE = 'GET_TRANSACTION'

export const ADD_CUSTOMER = 'ADD_TRANSACTION'
export const DELETE_CUSTOMER = 'DELETE_TRANSACTION'
export const UPDATE_CUSTOMER = 'UPDATE_TRANSACTION'
export const GET_CUSTOMER = 'GET_TRANSACTION'
export const CURRENT_CUSTOMER = 'GET_TRANSACTION'
